# Generated by Django 4.2.30 on 2026-07-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_nome_razao_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, default='', help_text='Apenas dígitos (14 caracteres)', max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cpf',
            field=models.CharField(blank=True, default='', help_text='Apenas dígitos (11 caracteres)', max_length=11, verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='AcionistaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cpf', models.CharField(blank=True, default='', max_length=11, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='whatsapp')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acionistas', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Acionista',
                'verbose_name_plural': 'Acionistas',
                'db_table': 'fornecedores_acionista',
                'ordering': ['-principal', 'nome'],
            },
        ),
    ]
