# Generated by Django 4.2.30 on 2026-07-26 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_alter_cliente_nome_razao_social'),
        ('portal', '0001_init_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessoportalcliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acessos_portal', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='acessoportalcliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acesso_portal', to=settings.AUTH_USER_MODEL),
        ),
    ]
