# Generated by Django 4.2.30 on 2026-08-05 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_copiar_documento_para_cpf_cnpj'),
        ('produtos', '0001_initial'),
        ('pagamentos', '0003_metodo_pagamento_remove_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0006_receita_data_estorno_receita_estornado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_venda', to='financeiro.conta')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_venda', to='pagamentos.metodopagamento')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento_venda_origem', to='financeiro.receita')),
            ],
            options={
                'db_table': 'pdv_pagamento_venda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('valor_fechamento_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_fechamento_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to='financeiro.conta')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdv_sessao_caixa',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='clientes.cliente')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to=settings.AUTH_USER_MODEL)),
                ('sessao_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='pdv.sessaocaixa')),
            ],
            options={
                'db_table': 'pdv_venda',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='RecebivelCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('taxa_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_liquido_previsto', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('data_prevista_liquidacao', models.DateField()),
                ('data_liquidacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='PREVISTO', max_length=10)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recebivel_cartao', to='pdv.pagamentovenda')),
                ('receita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recebivel_cartao', to='financeiro.receita')),
            ],
            options={
                'db_table': 'pdv_recebivel_cartao',
                'ordering': ['data_prevista_liquidacao'],
            },
        ),
        migrations.AddField(
            model_name='pagamentovenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pdv.venda'),
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('SANGRIA', 'Sangria'), ('SUPRIMENTO', 'Suprimento')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='pdv.sessaocaixa')),
            ],
            options={
                'db_table': 'pdv_movimento_caixa',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PT', 'Pacote'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('L', 'Litro'), ('M', 'Metro')], max_length=2)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Snapshot de Produto.preco_venda no momento da venda (RN-03).', max_digits=12)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('quantidade_estornada', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade devolvida parcialmente (RF-13).', max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda_pdv', to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pdv.venda')),
            ],
            options={
                'db_table': 'pdv_item_venda',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ABERTA')), fields=('conta',), name='uniq_sessao_aberta_por_conta'),
        ),
    ]
