# Generated by Django 4.2.30 on 2026-08-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ABERTA')), fields=('operador',), name='uniq_sessao_aberta_por_operador'),
        ),
    ]
