# Generated by Django 4.2.30 on 2026-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_razao_social',
            field=models.CharField(blank=True, max_length=255, verbose_name='nome / razão social'),
        ),
    ]
