# Generated by Django 4.2.30 on 2026-07-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_nome_razao_social'),
        ('vendas', '0001_init_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente'),
        ),
    ]
