# Generated by Django 4.2.30 on 2026-07-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0002_alter_itempedido_descricao_alter_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.orcamento')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='produtos.produto')),
            ],
            options={
                'db_table': 'vnd_item_orcamento',
                'ordering': ['id'],
            },
        ),
    ]
