# Generated by Django 4.2.30 on 2026-07-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_init_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromissos', to='agendamento.agenda'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
