# Generated by Django 4.2.30 on 2026-07-23 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('arquivo_nome', models.CharField(max_length=500)),
                ('periodo', models.DateField()),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado'), ('COM_DIVERGENCIAS', 'Com Divergencias')], default='PENDENTE', max_length=20)),
                ('total_banco', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('divergencias', models.IntegerField(default=0)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='financeiro.conta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_conciliacao_extrato',
                'ordering': ['-processado_em'],
            },
        ),
        migrations.CreateModel(
            name='PadraoSeguroConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_padrao', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('natureza', models.CharField(choices=[('APORTE', 'Aporte (capital social)'), ('RECEITA_FINANCEIRA', 'Receita Financeira (rendimento)')], default='APORTE', help_text='Apenas para tipo=ENTRADA: APORTE vai para PL; RECEITA_FINANCEIRA entra no DRE.', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_padrao_seguro_conciliacao',
                'ordering': ['tipo', 'descricao_padrao'],
            },
        ),
        migrations.CreateModel(
            name='ItemConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_banco', models.DateField()),
                ('descricao_banco', models.CharField(max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('status', models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('FALTANDO_SISTEMA', 'Faltando no Sistema'), ('FALTANDO_BANCO', 'Faltando no Banco')], max_length=20)),
                ('confirmado', models.BooleanField(default=False)),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.conciliacaoextrato')),
                ('lancamento_lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to='financeiro.livrocaixa')),
            ],
            options={
                'db_table': 'fin_item_conciliacao',
                'ordering': ['data_banco'],
            },
        ),
    ]
