# Generated by Django 4.2.30 on 2026-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_add_conciliacao_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='responsavel',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CAPITAL_SOCIAL', 'Capital Social'), ('SOCIO', 'Aporte do Fundador'), ('INVESTIDOR', 'Aporte de Investidor'), ('EMPRESTIMO', 'Empréstimo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10),
        ),
        migrations.AlterField(
            model_name='conta',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Poupança'), ('CAIXA', 'Caixa'), ('CARTEIRA', 'Carteira Digital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('FIXA', 'Despesa Fixa'), ('VARIAVEL', 'Despesa Variável'), ('PROLABORE', 'Pró-labore'), ('IMPOSTO', 'Imposto / DAS'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SERVICO', 'Serviço'), ('PRODUTO', 'Produto'), ('MENSALIDADE', 'Mensalidade'), ('RECEITA_FINANCEIRA', 'Receita Financeira'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receita',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
