# Generated by Django 4.2.30 on 2026-08-05 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0005_financeiro_basemodel_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data_estorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='estornado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receita',
            name='motivo_estorno',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EstornoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField()),
                ('data_estorno', models.DateField()),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_estorno_receita',
                'ordering': ['-data_estorno'],
            },
        ),
    ]
