# Generated by Django 4.2.30 on 2026-08-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
        ('financeiro', '0006_receita_data_estorno_receita_estornado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estornoreceita',
            name='item_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='pdv.itemvenda'),
        ),
        migrations.AddField(
            model_name='estornoreceita',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='financeiro.receita'),
        ),
    ]
