# Generated by Django 4.2.30 on 2026-07-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_nome_razao_social'),
        ('pagamentos', '0001_init_pagamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='nome',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO_CREDITO', 'Cartao de Credito'), ('CARTAO_DEBITO', 'Cartao de Debito'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='pagamentos.cobranca'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
