# Generated by Django 4.2.30 on 2026-07-31 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=50, verbose_name='código de barras')),
                ('quantidade_estoque', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade em estoque')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='estoque mínimo')),
                ('unidade_base', models.CharField(choices=[('UN', 'Unidade'), ('PT', 'Pacote'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('L', 'Litro'), ('M', 'Metro')], default='UN', max_length=2, verbose_name='unidade base')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor unitário (custo)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='preço de venda')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'prd_produto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PT', 'Pacote'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('L', 'Litro'), ('M', 'Metro')], max_length=2, verbose_name='unidade')),
                ('quantidade_base', models.DecimalField(decimal_places=3, default=0, help_text='Calculado automaticamente no save()', max_digits=12, verbose_name='quantidade em unidade base')),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=50, verbose_name='nota fiscal')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Entrada de Estoque',
                'verbose_name_plural': 'Entradas de Estoque',
                'db_table': 'prd_entrada_estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PT', 'Pacote'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('L', 'Litro'), ('M', 'Metro')], max_length=2, verbose_name='unidade')),
                ('quantidade_por_base', models.DecimalField(decimal_places=3, help_text='Ex: 1 CX = 30 UN → quantidade_por_base=30', max_digits=12, verbose_name='quantidade por unidade base')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Conversão de Unidade',
                'verbose_name_plural': 'Conversões de Unidade',
                'db_table': 'prd_conversao_unidade',
                'unique_together': {('produto', 'unidade')},
            },
        ),
    ]
