# Generated by Django 4.2.30 on 2026-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversaounidade',
            name='converte_para',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('PT', 'Pacote'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('L', 'Litro'), ('M', 'Metro')], help_text='Unidade de referência desta conversão (deve já existir como unidade_base do produto ou como outra ConversaoUnidade dele). Vazio = relativo à unidade_base do produto (comportamento legado, retrocompatível — Manutenção #37).', max_length=2, null=True, verbose_name='converte para'),
        ),
        migrations.AlterField(
            model_name='conversaounidade',
            name='quantidade_por_base',
            field=models.DecimalField(decimal_places=3, help_text='Quantos de `converte_para` (ou da unidade_base, se `converte_para` vazio) equivalem a 1 desta `unidade`. Ex: 1 CX = 30 UN → quantidade_por_base=30', max_digits=12, verbose_name='quantidade por unidade base'),
        ),
    ]
